# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=200)),
                ('to_email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('file', models.FileField(null=True, upload_to=b'files/')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default=b'sent', max_length=200)),
                ('important', models.BooleanField(default=False, max_length=10)),
            ],
        ),
    ]
