# Generated by Django 5.2.8 on 2025-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("common", "0002_enable_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="account_tags", to="common.tags"
            ),
        ),
    ]
