# Generated by Django 5.2.8 on 2025-12-08 03:05

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def cleanup_duplicate_account_names(apps, schema_editor):
    """
    Find duplicate account names (case-insensitive) within each org
    and append a numeric suffix to make them unique.
    """
    Account = apps.get_model("accounts", "Account")

    # Find duplicates: group by lower(name) + org, having count > 1
    duplicates = (
        Account.objects.annotate(name_lower=Lower("name"))
        .values("name_lower", "org_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        # Get all accounts with this name in this org, ordered by created_at
        accounts = list(
            Account.objects.filter(org_id=dup["org_id"])
            .annotate(name_lower=Lower("name"))
            .filter(name_lower=dup["name_lower"])
            .order_by("created_at")
        )

        # Keep the first one (oldest), rename the rest
        for i, account in enumerate(accounts[1:], start=2):
            original_name = account.name
            new_name = f"{account.name} ({i})"
            # Ensure the new name is also unique
            counter = i
            while Account.objects.filter(
                org_id=account.org_id, name__iexact=new_name
            ).exists():
                counter += 1
                new_name = f"{original_name} ({counter})"
            account.name = new_name
            account.save(update_fields=["name"])
            print(f"  Renamed duplicate account: '{original_name}' -> '{new_name}'")


def cleanup_negative_revenue(apps, schema_editor):
    """Set negative annual_revenue values to NULL."""
    Account = apps.get_model("accounts", "Account")
    updated = Account.objects.filter(annual_revenue__lt=0).update(annual_revenue=None)
    if updated:
        print(f"  Set {updated} negative annual_revenue values to NULL")


def reverse_noop(apps, schema_editor):
    """No reverse operation - data cleanup cannot be undone."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_add_currency_fields"),
        ("common", "0008_enable_rls_product_invoice_line_item"),
        ("contacts", "0009_alter_contact_created_by_alter_contact_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Run data cleanup BEFORE adding constraints
        migrations.RunPython(
            cleanup_duplicate_account_names,
            reverse_noop,
            elidable=True,
        ),
        migrations.RunPython(
            cleanup_negative_revenue,
            reverse_noop,
            elidable=True,
        ),
        # Now safe to add constraints
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (7-25 characters, digits and separators only)",
                        regex="^[\\d\\s\\-\\(\\)\\+\\.]{7,25}$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("org"),
                name="unique_account_name_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("annual_revenue__gte", 0),
                    ("annual_revenue__isnull", True),
                    _connector="OR",
                ),
                name="account_revenue_non_negative",
            ),
        ),
    ]
