# Generated by Django 4.2.1 on 2023-07-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teams',
            table='teams',
        ),
    ]
