# Generated by Django 3.2 on 2021-09-13 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0034_auto_20210913_1918"),
        ("teams", "0005_remove_teams_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="teams",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.company",
            ),
        ),
        migrations.AlterField(
            model_name="teams",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams_created",
                to="common.profile",
            ),
        ),
        migrations.AlterField(
            model_name="teams",
            name="users",
            field=models.ManyToManyField(
                related_name="user_teams", to="common.Profile"
            ),
        ),
    ]
