# Generated by Django 2.1.7 on 2019-02-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190210_1810'),
        ('contacts', '0002_auto_20190212_1334'),
    ]

    operations = [
    ]
