# Generated by Django 3.2.5 on 2021-07-16 10:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_remove_contact_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="phone",
            new_name="mobile_number",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="email",
            new_name="primary_email",
        ),
        migrations.AddField(
            model_name="contact",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="department",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Department"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="do_not_call",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="language",
            field=models.CharField(max_length=255, null=True, verbose_name="Language"),
        ),
        migrations.AddField(
            model_name="contact",
            name="linked_in_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="organization",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Organization"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="salutation",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Salutation"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="secondary_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="secondary_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="title",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="contact",
            name="twitter_username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
