# Generated by Django 2.1.7 on 2019-05-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20190315_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_from_site',
            field=models.BooleanField(default=False),
        ),
    ]
