# Generated by Django 3.1.7 on 2021-03-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0012_lead_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="company",
        ),
    ]
