# Generated by Django 3.1.7 on 2021-03-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0013_remove_lead_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="enquery_type",
            new_name="enquiry_type",
        ),
    ]
