stages:
  - build
  - deploy

buildstage:
  stage: build
  script:
    - df -h
    - cd /home/gitlab-runner/bottlecrm/deploy
    - git pull https://bottlecrm-runner:unbjh8yr9j9JYFSHGN83dh@gitx.micropyramid.com/bottlecrm/deploy master
    - . ../env/bin/activate
    - . .env
    - cd docker
    - ./buildimage.sh bottlecrm-runner unbjh8yr9j9JYFSHGN83dh
  only:
    - stage
  tags:
    - bottlecrm

deploystage:
  stage: deploy
  script:
    - df -h
    - cd /home/gitlab-runner/bottlecrm/deploy
    - git pull https://bottlecrm-runner:unbjh8yr9j9JYFSHGN83dh@gitx.micropyramid.com/bottlecrm/deploy master
    - . ../env/bin/activate
    - . .env
    - sudo /usr/bin/bash deploystage.sh
  only:
    - stage
  tags:
    - bottlecrm
