# Generated by Django 5.2.9 on 2026-02-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_replace_null_with_default_empty_on_char_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_org_id_9026a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderlineitem",
            name="order_line__org_id_444fcc_idx",
        ),
    ]
