# Generated by Django 6.0.7 on 2026-08-05 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_account_is_sample"),
        ("common", "0034_rls_pipeline_tables"),
        ("contacts", "0013_contact_is_sample"),
        (
            "invoices",
            "0010_estimate_accepted_by_email_estimate_accepted_by_name_and_more",
        ),
        ("opportunity", "0014_opportunity_is_sample"),
        ("orders", "0003_remove_order_orders_org_id_9026a7_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["org", "-created_at"], name="orders_org_id_9026a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderlineitem",
            index=models.Index(
                fields=["org", "-created_at"], name="order_line__org_id_444fcc_idx"
            ),
        ),
    ]
