# Generated by Django 2.2.4 on 2019-09-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicehistory',
            options={'ordering': ('created_on',)},
        ),
    ]
