# Generated by Django 3.2 on 2021-09-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_invoice_tax"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="company",
            new_name="org",
        ),
    ]
