strictness: medium

uses:
  - django

ignore-patterns:
  - migrations/

pylint:
  options:
    max-args: 10
  run: true
  disable:
    - redefined-builtin
    - unused-argument
    - cyclic-import
    - import-error
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - import-outside-toplevel
    - too-many-arguments
    - too-many-positional-arguments
    - too-many-nested-blocks
    - access-member-before-definition
    - wrong-import-position
    - unused-wildcard-import

mccabe:
  options:
    max-complexity: 30
