# Generated by Django 5.2.8 on 2025-11-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Phone"
            ),
        ),
    ]
