# Generated by Django 5.2.8 on 2025-12-02 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0004_change_phone_to_phonenumberfield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="linked_in_url",
            new_name="linkedin_url",
        ),
    ]
