# Generated by Django 5.2.8 on 2025-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_enable_rls"),
        ("contacts", "0005_rename_linked_in_url_to_linkedin_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="contact_tags", to="common.tags"
            ),
        ),
    ]
