# Generated by Django 5.2.8 on 2025-12-03 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_add_tags_related_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_organiz_8cebf0_idx",
        ),
    ]
