# Generated by Django 5.2.8 on 2025-12-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0007_remove_organization_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
    ]
