# Generated by Django 5.2.8 on 2025-12-08 03:05

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def cleanup_duplicate_contact_emails(apps, schema_editor):
    """
    Find duplicate contact emails (case-insensitive) within each org
    and clear email on duplicates (keep oldest).
    """
    Contact = apps.get_model("contacts", "Contact")

    # Find duplicates: group by lower(email) + org, having count > 1
    duplicates = (
        Contact.objects.exclude(email__isnull=True)
        .exclude(email="")
        .annotate(email_lower=Lower("email"))
        .values("email_lower", "org_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        # Get all contacts with this email in this org, ordered by created_at
        contacts = list(
            Contact.objects.filter(org_id=dup["org_id"])
            .exclude(email__isnull=True)
            .exclude(email="")
            .annotate(email_lower=Lower("email"))
            .filter(email_lower=dup["email_lower"])
            .order_by("created_at")
        )

        # Keep the first one (oldest), clear email on the rest
        for contact in contacts[1:]:
            old_email = contact.email
            contact.email = None
            contact.save(update_fields=["email"])
            print(f"  Cleared duplicate email on contact {contact.id}: '{old_email}'")


def reverse_noop(apps, schema_editor):
    """No reverse operation - data cleanup cannot be undone."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_enterprise_constraints"),
        ("common", "0008_enable_rls_product_invoice_line_item"),
        ("contacts", "0009_alter_contact_created_by_alter_contact_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Run data cleanup BEFORE adding constraints
        migrations.RunPython(
            cleanup_duplicate_contact_emails,
            reverse_noop,
            elidable=True,
        ),
        # Now safe to add constraints
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (7-25 characters, digits and separators only)",
                        regex="^[\\d\\s\\-\\(\\)\\+\\.]{7,25}$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("org"),
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                name="unique_contact_email_per_org",
            ),
        ),
    ]
