# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('case_type', models.CharField(blank=True, choices=[(b'Question', b'Question'), (b'Incident', b'Incident'), (b'Problem', b'Problem')], default=b'', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'New', b'New'), (b'Assigned', b'Assigned'), (b'Pending', b'Pending'), (b'Closed', b'Closed'), (b'Rejected', b'Rejected'), (b'Duplicate', b'Duplicate')], default=b'', max_length=64, null=True)),
                ('priority', models.CharField(blank=True, choices=[(b'Low', b'Low'), (b'Normal', b'Normal'), (b'High', b'High'), (b'Urgent', b'Urgent')], default=b'', max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('teams', models.CharField(blank=True, choices=[(b'Sales', b'Sales'), (b'Support', b'Support'), (b'TopManagement', b'TopManagement')], default=b'', max_length=64, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('account', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.LeadAccount')),
                ('contacts', models.ManyToManyField(blank=True, to='contacts.Contact')),
                ('userid', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('comment_file', models.FileField(default=b'', upload_to=b'media/comment_files', verbose_name=b'File')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('caseid', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.Case')),
                ('comment_user', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment_files',
            name='comment_id',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='cases.Comments'),
        ),
    ]
