# Generated by Django 4.2.1 on 2023-06-19 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('contacts', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ManyToManyField(related_name='case_assigned_users', to='common.profile'),
        ),
        migrations.AddField(
            model_name='case',
            name='contacts',
            field=models.ManyToManyField(to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_created_by', to='common.profile'),
        ),
        migrations.AddField(
            model_name='case',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_org', to='common.org'),
        ),
        migrations.AddField(
            model_name='case',
            name='teams',
            field=models.ManyToManyField(related_name='cases_teams', to='teams.teams'),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
    ]
