# Generated by Django 4.2.1 on 2023-07-21 11:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
