# Generated by Django 4.2.1 on 2023-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_org_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
