# Generated by Django 4.2.1 on 2024-02-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_org_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
