# Generated by Django 2.1.7 on 2019-02-14 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_to',
            field=models.ManyToManyField(related_name='document_shared_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
