# Generated by Django 2.1.7 on 2019-05-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_auto_20190524_1113"),
        ("common", "0013_auto_20190508_1540"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachments",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_attachment",
                to="invoices.Invoice",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_comments",
                to="invoices.Invoice",
            ),
        ),
    ]
