# Generated by Django 2.2.2 on 2019-07-22 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190624_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisettings',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created_on',)},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=50)),
                ('key_expires', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
