# Generated by Django 3.1 on 2021-01-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_auto_20200609_1203"),
    ]

    operations = [
        migrations.AddField(
            model_name="apisettings",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.company",
            ),
        ),
    ]
