# Generated by Django 3.1.6 on 2021-04-16 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_apisettings_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
