# Generated by Django 3.2.5 on 2021-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0032_remove_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="alternate_email",
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
