# Generated by Django 3.2 on 2021-09-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0034_auto_20210913_1918"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="sub_domain",
        ),
    ]
