# Generated by Django 3.2 on 2021-09-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_rename_company_event_org"),
        ("cases", "0009_rename_company_case_org"),
        ("teams", "0007_rename_company_teams_org"),
        ("leads", "0016_rename_company_lead_org"),
        ("contacts", "0009_rename_company_contact_org"),
        ("invoices", "0011_rename_company_invoice_org"),
        ("tasks", "0008_rename_company_task_org"),
        ("accounts", "0014_rename_company_account_org"),
        ("opportunity", "0008_rename_company_opportunity_org"),
        ("common", "0035_remove_company_sub_domain"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Company",
            new_name="Org",
        ),
        migrations.RenameField(
            model_name="apisettings",
            old_name="company",
            new_name="org",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="company",
            new_name="org",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="company",
            new_name="org",
        ),
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together={("user", "org")},
        ),
    ]
