# Generated by Django 3.2.7 on 2021-10-06 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_auto_20210922_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.org'),
        ),
    ]
