# Generated by Django 4.1 on 2022-09-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0041_user_key_expires"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="activation_key",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="key_expires",
        ),
    ]
