# Generated by Django 6.0.5 on 2026-05-09 21:10

import business_hours.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("business_calendar"))
        cursor.execute(get_enable_policy_sql("business_holiday"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("business_calendar"))
        cursor.execute(get_disable_policy_sql("business_holiday"))


def backfill_default_calendars(apps, schema_editor):
    """Create one Mon-Fri 9-5 UTC default calendar per existing org so that
    SLA timers immediately have a calendar to fall back on. Orgs already
    holding a default calendar are skipped (idempotent re-run safe)."""
    Org = apps.get_model("common", "Org")
    BusinessCalendar = apps.get_model("business_hours", "BusinessCalendar")
    nine = datetime.time(9, 0)
    five = datetime.time(17, 0)
    existing_org_ids = set(
        BusinessCalendar.objects.filter(is_default=True).values_list(
            "org_id", flat=True
        )
    )
    rows = []
    for org in Org.objects.exclude(id__in=existing_org_ids).iterator():
        rows.append(
            BusinessCalendar(
                org=org,
                name="Default",
                timezone="UTC",
                is_default=True,
                monday_open=nine,
                monday_close=five,
                tuesday_open=nine,
                tuesday_close=five,
                wednesday_open=nine,
                wednesday_close=five,
                thursday_open=nine,
                thursday_close=five,
                friday_open=nine,
                friday_close=five,
            )
        )
    if rows:
        BusinessCalendar.objects.bulk_create(rows)


def remove_default_calendars(apps, schema_editor):
    BusinessCalendar = apps.get_model("business_hours", "BusinessCalendar")
    BusinessCalendar.objects.filter(name="Default", is_default=True).delete()


class Migration(migrations.Migration):

    initial = True

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('common', '0018_add_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone (e.g. America/New_York).', max_length=64, validators=[business_hours.models._validate_iana_tz])),
                ('is_default', models.BooleanField(default=True)),
                ('monday_open', models.TimeField(blank=True, null=True)),
                ('monday_close', models.TimeField(blank=True, null=True)),
                ('tuesday_open', models.TimeField(blank=True, null=True)),
                ('tuesday_close', models.TimeField(blank=True, null=True)),
                ('wednesday_open', models.TimeField(blank=True, null=True)),
                ('wednesday_close', models.TimeField(blank=True, null=True)),
                ('thursday_open', models.TimeField(blank=True, null=True)),
                ('thursday_close', models.TimeField(blank=True, null=True)),
                ('friday_open', models.TimeField(blank=True, null=True)),
                ('friday_close', models.TimeField(blank=True, null=True)),
                ('saturday_open', models.TimeField(blank=True, null=True)),
                ('saturday_close', models.TimeField(blank=True, null=True)),
                ('sunday_open', models.TimeField(blank=True, null=True)),
                ('sunday_close', models.TimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_calendars', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Business Calendar',
                'verbose_name_plural': 'Business Calendars',
                'db_table': 'business_calendar',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BusinessHoliday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='business_hours.businesscalendar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_holidays', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Business Holiday',
                'verbose_name_plural': 'Business Holidays',
                'db_table': 'business_holiday',
                'ordering': ('date',),
            },
        ),
        migrations.AddIndex(
            model_name='businesscalendar',
            index=models.Index(fields=['org', 'is_default'], name='business_ca_org_id_e518f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='businesscalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('org',), name='uniq_default_business_calendar_per_org'),
        ),
        migrations.AddIndex(
            model_name='businessholiday',
            index=models.Index(fields=['calendar', 'date'], name='business_ho_calenda_8e023f_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessholiday',
            constraint=models.UniqueConstraint(fields=('calendar', 'date'), name='uniq_business_holiday_per_calendar_date'),
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
        migrations.RunPython(
            backfill_default_calendars,
            reverse_code=remove_default_calendars,
        ),
    ]
