# Generated by Django 2.1.7 on 2019-03-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20190315_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
