# Generated by Django 2.2.4 on 2019-09-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_auto_20190904_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duplicatecontacts',
            options={'ordering': ('id',)},
        ),
    ]
