# Generated by Django 3.0 on 2020-11-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_auto_20200912_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='failedcontact',
            old_name='contry',
            new_name='country',
        ),
    ]
