# Generated by Django 5.2.8 on 2025-12-02 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_initial"),
        ("leads", "0002_add_converted_account_fk"),
        ("opportunity", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="case_tasks",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lead_tasks",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunity_tasks",
                to="opportunity.opportunity",
            ),
        ),
    ]
