# Generated by Django 5.2.8 on 2025-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_enable_rls"),
        ("tasks", "0004_add_tags_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="task_tags", to="common.tags"
            ),
        ),
    ]
