# Generated by Django 5.2.8 on 2025-12-08 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_board_created_by_alter_board_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
