# Generated by Django 5.2.9 on 2025-12-09 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_task_kanban"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="task_status_e6f973_idx",
            old_name="task_status_kanban_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_stage_i_a7a1b0_idx",
            old_name="task_stage_kanban_idx",
        ),
        migrations.RenameIndex(
            model_name="taskpipeline",
            new_name="task_pipeli_org_id_5f31c6_idx",
            old_name="task_pipeline_org_idx",
        ),
        migrations.RenameIndex(
            model_name="taskstage",
            new_name="task_stage_org_id_cfad78_idx",
            old_name="task_stage_org_order_idx",
        ),
        migrations.RenameIndex(
            model_name="taskstage",
            new_name="task_stage_pipelin_f4ed15_idx",
            old_name="task_stage_pipeline_idx",
        ),
    ]
