# Generated by Django 6.0.7 on 2026-08-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_task_is_sample"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskpipeline",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Sorts this pipeline first in listings (see Meta.ordering) and is limited to one per org. It does NOT route new records: a task created without a stage keeps stage=NULL, which is the supported status-based kanban mode.",
            ),
        ),
    ]
