# Generated by Django 2.1.7 on 2019-05-17 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='assigned_to',
            field=models.ManyToManyField(related_name='account_assigned_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
