FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG PIP_EXTRA_INDEX_URL

WORKDIR /app

# Intall dependencies
COPY requirements.txt /app

RUN apt update
RUN apt install -y git ruby-dev ruby-ffi postgresql-client redis-server wkhtmltopdf
RUN apt clean
RUN gem install sass
RUN gem install compass
# install nvm/npm
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN apt install nodejs npm -y
RUN npm -g install less
RUN apt install -y python3-pip
RUN python3 -m pip install --no-cache-dir -r requirements.txt
RUN python3 -m pip install --no-cache-dir redis

RUN python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())' > /app/secret_key.txt
ENV SECRET_KEY \
    $(cat /app/secret_key.txt)
RUN rm /app/secret_key.txt


COPY . /app
COPY docker/entrypoint.sh /app
COPY docker/wait-for-postgres.sh /app


RUN chmod +x entrypoint.sh 
RUN chmod +x wait-for-postgres.sh
ENTRYPOINT ["./entrypoint.sh"]
