FROM common-bottle-dockerfile

RUN gem install sass
RUN gem install compass
# install nvm/npm
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
RUN apt install nodejs npm -y
RUN npm -g install less

RUN apt install -y postgresql-client

# Install dependencies
COPY requirements.txt /app

RUN python3 -m pip install --no-cache-dir -r requirements.txt
COPY . /app
COPY docker/entrypoint.sh /app
COPY docker/wait-for-postgres.sh /app

RUN chmod +x entrypoint.sh 
RUN chmod +x wait-for-postgres.sh
ENTRYPOINT ["./entrypoint.sh"]
