FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Install dependencies
COPY requirements.txt /app
COPY docker/entrypoint.sh /app
COPY docker/wait-for-postgres.sh /app

RUN apt-get update \
    && apt-get install -y git ruby-dev ruby-ffi postgresql-client redis-server wkhtmltopdf \
    && apt-get clean \
    && gem install sass compass \
    && apt-get install -y nodejs npm \
    && npm install -g less \
    && apt-get install -y python3-pip \
    && python3 -m pip install --no-cache-dir -r requirements.txt redis \
    && chmod +x entrypoint.sh wait-for-postgres.sh

COPY . /app
ENTRYPOINT ["./entrypoint.sh"]