# Generated by Django 3.1.7 on 2021-03-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="company",
        ),
    ]
