# Generated by Django 2.1.5 on 2019-02-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_status'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounts.Tags'),
        ),
    ]
