# Generated by Django 3.1.7 on 2021-03-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_teams_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teams",
            name="company",
        ),
    ]
