# Generated by Django 5.2.8 on 2025-12-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_enable_rls"),
        ("opportunity", "0002_add_tags_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="assigned_to",
            field=models.ManyToManyField(
                related_name="opportunity_assigned_users", to="common.profile"
            ),
        ),
    ]
