# Generated by Django 5.2.8 on 2025-12-06 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0003_alter_opportunity_assigned_to"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "USD, Dollar"),
                    ("EUR", "EUR, Euro"),
                    ("GBP", "GBP, Pound"),
                    ("INR", "INR, Rupee"),
                    ("CAD", "CAD, Dollar"),
                    ("AUD", "AUD, Dollar"),
                    ("JPY", "JPY, Yen"),
                    ("CNY", "CNY, Yuan"),
                    ("CHF", "CHF, Franc"),
                    ("SGD", "SGD, Dollar"),
                    ("AED", "AED, Dirham"),
                    ("BRL", "BRL, Real"),
                    ("MXN", "MXN, Peso"),
                ],
                max_length=3,
                null=True,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Modified By",
            ),
        ),
    ]
