# Generated by Django 5.2.8 on 2025-12-08 03:05

from django.conf import settings
from django.db import migrations, models


def cleanup_invalid_probability(apps, schema_editor):
    """Fix probability values outside 0-100 range."""
    Opportunity = apps.get_model("opportunity", "Opportunity")

    # Set negative probabilities to 0
    updated = Opportunity.objects.filter(probability__lt=0).update(probability=0)
    if updated:
        print(f"  Set {updated} negative probability values to 0")

    # Set probabilities over 100 to 100
    updated = Opportunity.objects.filter(probability__gt=100).update(probability=100)
    if updated:
        print(f"  Set {updated} probability values over 100 to 100")


def cleanup_negative_amounts(apps, schema_editor):
    """Set negative amount values to NULL."""
    Opportunity = apps.get_model("opportunity", "Opportunity")
    updated = Opportunity.objects.filter(amount__lt=0).update(amount=None)
    if updated:
        print(f"  Set {updated} negative amount values to NULL")


def reverse_noop(apps, schema_editor):
    """No reverse operation - data cleanup cannot be undone."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_add_enterprise_constraints"),
        ("common", "0008_enable_rls_product_invoice_line_item"),
        ("contacts", "0010_add_enterprise_constraints"),
        ("opportunity", "0004_alter_opportunity_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Run data cleanup BEFORE adding constraints
        migrations.RunPython(
            cleanup_invalid_probability,
            reverse_noop,
            elidable=True,
        ),
        migrations.RunPython(
            cleanup_negative_amounts,
            reverse_noop,
            elidable=True,
        ),
        # Now safe to add constraints
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(("probability__gte", 0), ("probability__lte", 100)),
                name="opportunity_probability_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount__gte", 0), ("amount__isnull", True), _connector="OR"
                ),
                name="opportunity_amount_non_negative",
            ),
        ),
    ]
