# Generated by Django 5.2.9 on 2025-12-09 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0006_add_opportunity_line_item"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="opportunitylineitem",
            new_name="opportunity_opportu_456e8f_idx",
            old_name="opportunity__opportu_5e4c7e_idx",
        ),
        migrations.RenameIndex(
            model_name="opportunitylineitem",
            new_name="opportunity_org_id_c76c2c_idx",
            old_name="opportunity__org_id_a1b2c3_idx",
        ),
        migrations.AlterField(
            model_name="opportunitylineitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="opportunitylineitem",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="opportunitylineitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
        ),
    ]
