# Generated by Django 5.2.11 on 2026-02-18 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_stage_changed_at(apps, schema_editor):
    """Set stage_changed_at = created_at for existing opportunities."""
    Opportunity = apps.get_model('opportunity', 'Opportunity')
    Opportunity.objects.filter(stage_changed_at__isnull=True).update(
        stage_changed_at=models.F('created_at')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_add_tag_color_description_isactive'),
        ('opportunity', '0007_rename_opportunity__opportu_5e4c7e_idx_opportunity_opportu_456e8f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stage Changed At'),
        ),
        migrations.RunPython(backfill_stage_changed_at, migrations.RunPython.noop),
        migrations.CreateModel(
            name='StageAgingConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage', models.CharField(choices=[('PROSPECTING', 'Prospecting'), ('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], max_length=64, verbose_name='Stage')),
                ('expected_days', models.PositiveIntegerField(default=14, verbose_name='Expected Days')),
                ('warning_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Warning Days')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_aging_configs', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Stage Aging Config',
                'verbose_name_plural': 'Stage Aging Configs',
                'db_table': 'stage_aging_config',
                'unique_together': {('org', 'stage')},
            },
        ),
    ]
