# Generated by Django 5.2.11 on 2026-02-18 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_add_tag_color_description_isactive'),
        ('opportunity', '0008_add_stage_aging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGoal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Goal Name')),
                ('goal_type', models.CharField(choices=[('REVENUE', 'Revenue'), ('DEALS_CLOSED', 'Deals Closed')], max_length=20, verbose_name='Goal Type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Value')),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='Period Type')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('is_active', models.BooleanField(default=True)),
                ('milestone_50_notified', models.BooleanField(default=False)),
                ('milestone_90_notified', models.BooleanField(default=False)),
                ('milestone_100_notified', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_goals', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to='common.org')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_goals', to='common.teams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Sales Goal',
                'verbose_name_plural': 'Sales Goals',
                'db_table': 'sales_goal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['org', '-created_at'], name='sales_goal_org_id_363225_idx'), models.Index(fields=['org', 'period_start', 'period_end'], name='sales_goal_org_id_f5e0bd_idx')],
            },
        ),
    ]
