# Generated by Django 2.2.10 on 2020-04-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_auto_20200409_1653"),
        ("accounts", "0010_account_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.Company",
            ),
        ),
    ]
