# Generated by Django 3.1.7 on 2021-03-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="company",
        ),
    ]
