# Generated by Django 5.2.8 on 2025-12-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="invoicehistory",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
