# Generated by Django 5.2.9 on 2025-12-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_estimate_estimatelineitem_invoicetemplate_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimatelineitem",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Item Name"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_period",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Billing Period"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="po_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="PO Number"
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Item Name"
            ),
        ),
        migrations.AddField(
            model_name="recurringinvoicelineitem",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Item Name"
            ),
        ),
        migrations.AlterField(
            model_name="estimatelineitem",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvoicelineitem",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Description"
            ),
        ),
    ]
