# Generated by Django 5.2.9 on 2025-12-08 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_add_billing_period_po_number_and_lineitem_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="rate",
        ),
    ]
