# Generated by Django 5.2.9 on 2025-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0006_remove_legacy_invoice_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Cancelled At"
            ),
        ),
    ]
