# Generated by Django 5.2.8 on 2025-12-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_enable_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentfiles",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_files",
                to="common.org",
            ),
        ),
    ]
