# Generated by Django 5.2.8 on 2025-12-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_populate_commentfiles_org_and_rls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apisettings",
            name="apikey",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
