# Generated by Django 5.2.8 on 2025-12-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_increase_apikey_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="alternate_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
