# Generated by Django 5.2.9 on 2025-12-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_enable_rls_opportunity_line_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tags",
            options={
                "ordering": ("name",),
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AddField(
            model_name="tags",
            name="color",
            field=models.CharField(
                choices=[
                    ("gray", "Gray"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("amber", "Amber"),
                    ("yellow", "Yellow"),
                    ("lime", "Lime"),
                    ("green", "Green"),
                    ("emerald", "Emerald"),
                    ("teal", "Teal"),
                    ("cyan", "Cyan"),
                    ("sky", "Sky"),
                    ("blue", "Blue"),
                    ("indigo", "Indigo"),
                    ("violet", "Violet"),
                    ("purple", "Purple"),
                    ("fuchsia", "Fuchsia"),
                    ("pink", "Pink"),
                    ("rose", "Rose"),
                ],
                default="blue",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tags",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tags",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tags",
            name="slug",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
