# Generated by Django 5.2.9 on 2026-02-21 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_enable_rls_orders_salesforce"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagicLinkToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "db_table": "magic_link_token",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="magic_link__email_13ce49_idx",
                    )
                ],
            },
        ),
    ]
