# Generated by Django 6.0.5 on 2026-05-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_activity_metadata_alter_activity_action'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id', 'is_internal'], name='comment_content_7e7d4c_idx'),
        ),
    ]
