# Generated by Django 6.0.5 on 2026-05-09 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("custom_field_definition"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("custom_field_definition"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('common', '0016_add_comment_is_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_model', models.CharField(choices=[('Case', 'Case'), ('Lead', 'Lead'), ('Contact', 'Contact'), ('Task', 'Task'), ('Opportunity', 'Opportunity')], max_length=32)),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('date', 'Date'), ('checkbox', 'Checkbox')], max_length=16)),
                ('options', models.JSONField(blank=True, help_text='List of {value, label} pairs for dropdown fields.', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Custom Field Definition',
                'verbose_name_plural': 'Custom Field Definitions',
                'db_table': 'custom_field_definition',
                'ordering': ('target_model', 'display_order', 'label'),
                'indexes': [models.Index(fields=['org', 'target_model', 'is_active'], name='custom_fiel_org_id_4b73e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'target_model', 'key'), name='uniq_custom_field_per_org_target')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
