# Generated by Django 6.0.5 on 2026-05-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_activity_analytics_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='csat_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
