# Generated by Django 6.0.5 on 2026-05-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_org_auto_close_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('COMMENT', 'Commented'), ('ASSIGN', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('PRIORITY_CHANGED', 'Priority Changed'), ('ROUTED', 'Routed'), ('ESCALATED', 'Escalated'), ('REOPENED', 'Reopened'), ('MERGED', 'Merged'), ('MERGE_TARGET', 'Merge Target'), ('UNMERGED', 'Unmerged'), ('UNMERGE_TARGET', 'Unmerge Target'), ('LINKED_SOLUTION', 'Linked Solution'), ('UNLINKED_SOLUTION', 'Unlinked Solution'), ('WATCHED', 'Watched'), ('UNWATCHED', 'Unwatched'), ('MENTIONED', 'Mentioned'), ('APPROVAL_REQUESTED', 'Approval Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPROVAL_CANCELLED', 'Approval Cancelled'), ('LINKED_ASSET', 'Linked Asset'), ('UNLINKED_ASSET', 'Unlinked Asset'), ('LINKED_JIRA', 'Linked Jira'), ('LINKED_PARENT', 'Linked Parent'), ('UNLINKED_PARENT', 'Unlinked Parent'), ('PARENT_CLOSED_CASCADE', 'Parent Closed Cascade'), ('TIME_LOGGED', 'Time Logged')], max_length=32),
        ),
    ]
