# Generated by Django 6.0.5 on 2026-05-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_alter_activity_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='target_model',
            field=models.CharField(choices=[('Account', 'Account'), ('Case', 'Case'), ('Contact', 'Contact'), ('Invoice', 'Invoice'), ('Lead', 'Lead'), ('Opportunity', 'Opportunity'), ('Task', 'Task')], max_length=32),
        ),
    ]
