# Generated by Django 6.0.5 on 2026-05-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0025_magic_link_token_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="name"
            ),
        ),
    ]
