# Generated by Django 6.0.7 on 2026-07-30 18:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0029_delete_sessiontoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("estimate", "Estimate"),
                            ("csat", "CSAT survey"),
                        ],
                        max_length=16,
                    ),
                ),
                ("resource_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_access_tokens",
                        to="common.org",
                    ),
                ),
            ],
            options={
                "db_table": "portal_access_token",
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="portal_acce_resourc_e9c0d2_idx",
                    )
                ],
            },
        ),
    ]
