# Generated by Django 6.0.7 on 2026-08-01 11:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("pack_application"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("pack_application"))


class Migration(migrations.Migration):
    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ("common", "0031_backfill_portal_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="terminology",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Label overrides, e.g. {'lead.plural': 'Enquiries'}.",
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="vertical",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pack id applied to this org, e.g. 'real-estate'. Descriptive only.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="PackApplication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("pack_id", models.CharField(max_length=64)),
                ("pack_version", models.PositiveIntegerField()),
                (
                    "result",
                    models.JSONField(
                        default=dict,
                        help_text="{'created': [...], 'skipped': [...], 'failed': [...]}",
                    ),
                ),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pack_applications",
                        to="common.profile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="Organization this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack Application",
                "verbose_name_plural": "Pack Applications",
                "db_table": "pack_application",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["org", "-created_at"],
                        name="pack_applic_org_id_78eec5_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
