# Generated by Django 5.2.8 on 2025-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_fix_contacts_related_name"),
        ("common", "0002_enable_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="tags",
            field=models.ManyToManyField(blank=True, to="common.tags"),
        ),
    ]
