# Generated by Django 5.2.8 on 2025-12-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0005_add_tags_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Question", "Question"),
                    ("Incident", "Incident"),
                    ("Problem", "Problem"),
                ],
                default=None,
                max_length=255,
                null=True,
            ),
        ),
    ]
