# Generated by Django 5.2.8 on 2025-12-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0007_alter_case_created_by_alter_case_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="first_response_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="First Response At"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Resolved At"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="sla_first_response_hours",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Target hours for first response",
                verbose_name="First Response SLA (hours)",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="sla_resolution_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Target hours for resolution",
                verbose_name="Resolution SLA (hours)",
            ),
        ),
    ]
