# Generated by Django 5.2.9 on 2025-12-09 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # Disable atomic mode to avoid "pending trigger events" error from RLS policies
    atomic = False

    dependencies = [
        ("accounts", "0006_add_enterprise_constraints"),
        ("cases", "0008_add_enterprise_constraints"),
        ("common", "0012_add_tag_color_description_isactive"),
        ("contacts", "0010_add_enterprise_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="kanban_order",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Order within the kanban column for drag-drop positioning",
                max_digits=15,
                verbose_name="Kanban Order",
            ),
        ),
        migrations.CreateModel(
            name="CasePipeline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Pipeline Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If true, new cases without explicit pipeline go here",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_pipelines",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Pipeline",
                "verbose_name_plural": "Case Pipelines",
                "db_table": "case_pipeline",
                "ordering": ("-is_default", "name"),
            },
        ),
        migrations.CreateModel(
            name="CaseStage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Stage Name")),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "maps_to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "New"),
                            ("Assigned", "Assigned"),
                            ("Pending", "Pending"),
                            ("Closed", "Closed"),
                            ("Rejected", "Rejected"),
                            ("Duplicate", "Duplicate"),
                        ],
                        help_text="When case enters this stage, also update Case.status",
                        max_length=64,
                        null=True,
                        verbose_name="Maps to Status",
                    ),
                ),
                (
                    "wip_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum cases allowed in this stage (null = unlimited)",
                        null=True,
                        verbose_name="WIP Limit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_stages",
                        to="common.org",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="cases.casepipeline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Stage",
                "verbose_name_plural": "Case Stages",
                "db_table": "case_stage",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="case",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Current pipeline stage (null = use status-based kanban)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="cases.casestage",
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["stage", "kanban_order"], name="case_stage_i_f04bec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(
                fields=["status", "kanban_order"], name="case_status_a33019_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casepipeline",
            index=models.Index(
                fields=["org", "-created_at"], name="case_pipeli_org_id_f4590e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="casepipeline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("org",),
                name="unique_default_case_pipeline_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="casestage",
            index=models.Index(
                fields=["org", "order"], name="case_stage_org_id_b9d581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casestage",
            index=models.Index(
                fields=["pipeline", "order"], name="case_stage_pipelin_3fbf31_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="casestage",
            unique_together={("pipeline", "name")},
        ),
    ]
