# Generated by Django 6.0.5 on 2026-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_reopen_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Per-org schema extension; values are validated against common.CustomFieldDefinition.'),
        ),
    ]
