# Generated by Django 6.0.5 on 2026-05-09 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("escalation_policy"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("escalation_policy"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('cases', '0011_case_custom_fields'),
        ('common', '0017_customfielddefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='escalation_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='last_escalation_fired_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Escalation Fired At'),
        ),
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=64)),
                ('first_response_action', models.CharField(choices=[('notify', 'Notify'), ('reassign', 'Reassign'), ('notify_and_reassign', 'Notify and reassign')], default='notify', max_length=32)),
                ('resolution_action', models.CharField(choices=[('notify', 'Notify'), ('reassign', 'Reassign'), ('notify_and_reassign', 'Notify and reassign')], default='notify', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('first_response_target', models.ForeignKey(blank=True, help_text='Profile reassigned to and/or notified on first-response breach.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_response_escalation_policies', to='common.profile')),
                ('notify_team', models.ForeignKey(blank=True, help_text="Optional team CC'd on either breach action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to='common.teams')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_policies', to='common.org')),
                ('resolution_target', models.ForeignKey(blank=True, help_text='Profile reassigned to and/or notified on resolution breach.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_escalation_policies', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Escalation Policy',
                'verbose_name_plural': 'Escalation Policies',
                'db_table': 'escalation_policy',
                'ordering': ('priority',),
                'indexes': [models.Index(fields=['org', 'is_active'], name='escalation__org_id_4bf36d_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'priority'), name='uniq_escalation_policy_per_org_priority')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
