# Generated by Django 6.0.5 on 2026-05-09 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("inbound_mailbox"))
        cursor.execute(get_enable_policy_sql("email_message"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("inbound_mailbox"))
        cursor.execute(get_disable_policy_sql("email_message"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('cases', '0012_escalation'),
        ('common', '0017_customfielddefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='external_thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=16)),
                ('message_id', models.CharField(db_index=True, max_length=512)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('references', models.TextField(blank=True, default='', help_text='Whitespace-separated list of RFC-5322 Message-IDs from the References header.')),
                ('from_address', models.EmailField(max_length=254)),
                ('to_addresses', models.TextField(blank=True, default='')),
                ('cc_addresses', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField()),
                ('drop_reason', models.CharField(blank=True, default='', help_text='If non-empty, the message was rejected (spam/bounce/etc.) before any Case was touched. `case` will be null in this case.', max_length=64)),
                ('case', models.ForeignKey(blank=True, help_text='Null when the message was dropped (spam/bounce/auto-reply) but we still want an audit trail.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'db_table': 'email_message',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['org', '-received_at'], name='email_messa_org_id_631bc3_idx'), models.Index(fields=['case', '-received_at'], name='email_messa_case_id_bc66f7_idx'), models.Index(fields=['in_reply_to'], name='email_messa_in_repl_216d84_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'message_id'), name='uniq_email_message_per_org_id')],
            },
        ),
        migrations.CreateModel(
            name='InboundMailbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.EmailField(max_length=254, verbose_name='Inbound Address')),
                ('provider', models.CharField(choices=[('ses', 'AWS SES (SNS direct delivery)'), ('mailgun', 'Mailgun'), ('postmark', 'Postmark'), ('imap', 'IMAP')], default='ses', max_length=16)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Shared secret / SNS Topic ARN suffix used to verify webhook calls. Auto-generated on create if left blank.', max_length=128)),
                ('imap_host', models.CharField(blank=True, default='', max_length=255)),
                ('imap_port', models.PositiveIntegerField(blank=True, null=True)),
                ('imap_username', models.CharField(blank=True, default='', max_length=255)),
                ('imap_password_enc', models.CharField(blank=True, default='', max_length=512)),
                ('default_priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=64)),
                ('default_case_type', models.CharField(blank=True, choices=[('Question', 'Question'), ('Incident', 'Incident'), ('Problem', 'Problem')], max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_inbound_mailboxes', to='common.profile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_mailboxes', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Inbound Mailbox',
                'verbose_name_plural': 'Inbound Mailboxes',
                'db_table': 'inbound_mailbox',
                'ordering': ('address',),
                'indexes': [models.Index(fields=['org', 'is_active'], name='inbound_mai_org_id_0a00ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'address'), name='uniq_inbound_mailbox_per_org_address')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
