# Generated by Django 6.0.5 on 2026-05-09 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("routing_rule"))
        cursor.execute(get_enable_policy_sql("routing_rule_state"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("routing_rule"))
        cursor.execute(get_disable_policy_sql("routing_rule_state"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('cases', '0013_inbound_email'),
        ('common', '0017_customfielddefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('priority_order', models.PositiveIntegerField(db_index=True, default=100, help_text='Lower runs first; ties broken by created_at.')),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, default=list, help_text='List of {field, op, value} triples; AND across entries.')),
                ('strategy', models.CharField(choices=[('round_robin', 'Round-robin within target_assignees'), ('least_busy', 'Least busy in target_assignees'), ('direct', 'Single profile in target_assignees'), ('by_team', 'Assign to target_team')], default='direct', max_length=16)),
                ('stop_processing', models.BooleanField(default=True, help_text='If a rule matches and this is True, skip lower-priority rules.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='common.org')),
                ('target_assignees', models.ManyToManyField(blank=True, related_name='routing_rules', to='common.profile')),
                ('target_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='common.teams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Routing Rule',
                'verbose_name_plural': 'Routing Rules',
                'db_table': 'routing_rule',
                'ordering': ('priority_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RoutingRuleState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_assigned_index', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rule_states', to='common.org')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='cases.routingrule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Routing Rule State',
                'verbose_name_plural': 'Routing Rule States',
                'db_table': 'routing_rule_state',
            },
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['org', 'is_active', 'priority_order'], name='rr_eval_idx'),
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
