# Generated by Django 6.0.5 on 2026-05-09 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("case_watcher"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("case_watcher"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('cases', '0015_merge'),
        ('common', '0018_add_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseWatcher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subscribed_via', models.CharField(choices=[('manual', 'Manual'), ('mention', 'Mention'), ('auto_assignee', 'Auto (Assignee)'), ('auto_team', 'Auto (Team)')], default='manual', max_length=16)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_rows', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_watchers', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_cases', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Case Watcher',
                'verbose_name_plural': 'Case Watchers',
                'db_table': 'case_watcher',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='case',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='case_watching', through='cases.CaseWatcher', to='common.profile'),
        ),
        migrations.AddIndex(
            model_name='casewatcher',
            index=models.Index(fields=['profile', '-created_at'], name='case_watche_profile_88025c_idx'),
        ),
        migrations.AddIndex(
            model_name='casewatcher',
            index=models.Index(fields=['case'], name='case_watche_case_id_09be35_idx'),
        ),
        migrations.AddConstraint(
            model_name='casewatcher',
            constraint=models.UniqueConstraint(fields=('case', 'profile'), name='uniq_case_watcher_per_profile'),
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
