# Generated by Django 6.0.5 on 2026-05-09 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("csat_survey"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("csat_survey"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('cases', '0018_case_resolved_idx'),
        ('common', '0020_org_csat_enabled'),
        ('contacts', '0011_inbound_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsatSurvey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.DateTimeField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csat_survey', to='cases.case')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csat_surveys', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csat_surveys', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'CSAT Survey',
                'verbose_name_plural': 'CSAT Surveys',
                'db_table': 'csat_survey',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['org', '-responded_at'], name='csat_survey_org_id_a284b2_idx'), models.Index(fields=['case'], name='csat_survey_case_id_516193_idx'), models.Index(fields=['token_hash'], name='csat_survey_token_h_2f45f7_idx')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
