# Generated by Django 6.0.5 on 2026-05-10 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("time_entry"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("time_entry"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('cases', '0020_case_parent_is_problem'),
        ('common', '0021_org_auto_close_children'),
        ('invoices', '0007_add_cancelled_at_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, help_text='Null while the timer is running.', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Recomputed on save when both timestamps are present.')),
                ('description', models.TextField(blank=True, default='')),
                ('billable', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot at log time so future rate changes do not alter history.', max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD, Dollar'), ('EUR', 'EUR, Euro'), ('GBP', 'GBP, Pound'), ('INR', 'INR, Rupee'), ('CAD', 'CAD, Dollar'), ('AUD', 'AUD, Dollar'), ('JPY', 'JPY, Yen'), ('CNY', 'CNY, Yuan'), ('CHF', 'CHF, Franc'), ('SGD', 'SGD, Dollar'), ('AED', 'AED, Dirham'), ('BRL', 'BRL, Real'), ('MXN', 'MXN, Peso')], default='USD', max_length=3)),
                ('auto_stopped', models.BooleanField(default=False, help_text='Set by the auto-stop Celery task when a forgotten timer is killed.')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('invoice', models.ForeignKey(blank=True, help_text='Set when this entry has been pushed to a draft invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='invoices.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='common.org')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'db_table': 'time_entry',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['org', 'profile', 'started_at'], name='time_entry_org_id_93126d_idx'), models.Index(fields=['case', 'started_at'], name='time_entry_case_id_b266ff_idx'), models.Index(fields=['billable', 'invoice'], name='time_entry_billabl_2174a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='time_entry_end_after_start'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('profile',), name='one_active_timer_per_profile')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
