# Generated by Django 6.0.5 on 2026-05-10 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("approval_rule"))
        cursor.execute(get_enable_policy_sql("approval"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("approval"))
        cursor.execute(get_disable_policy_sql("approval_rule"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('cases', '0021_timeentry'),
        ('common', '0021_org_auto_close_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('trigger_event', models.CharField(choices=[('pre_close', 'Pre-Close')], default='pre_close', max_length=16)),
                ('match_priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=32, null=True)),
                ('match_case_type', models.CharField(blank=True, choices=[('Question', 'Question'), ('Incident', 'Incident'), ('Problem', 'Problem')], max_length=32, null=True)),
                ('approver_role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager')], default='ADMIN', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('approvers', models.ManyToManyField(blank=True, related_name='approval_rules', to='common.profile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('match_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rules', to='common.teams')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Approval Rule',
                'verbose_name_plural': 'Approval Rules',
                'db_table': 'approval_rule',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_assigned', to='common.profile')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='common.org')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_requested', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='cases.approvalrule')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'db_table': 'approval',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['org', 'trigger_event', 'is_active'], name='approval_rule_match_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['org', 'state'], name='approval_org_state_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['case', 'state'], name='approval_case_state_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['approver', 'state'], name='approval_approver_idx'),
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
