# Generated by Django 6.0.5 on 2026-05-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_approvalrule_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='merge_record',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
