# Generated by Django 6.0.7 on 2026-07-30 16:50

import django.db.models.deletion
from django.db import migrations, models


def backfill_mailbox(apps, schema_editor):
    """Attribute existing EmailMessage rows to a mailbox by matching the To
    header against each mailbox's address (per org).

    Best-effort historical attribution: this is the same signal a proxy would
    use, so rows delivered by BCC/alias/forwarding (where the address is not in
    the To header) stay null. All NEW inbound mail is attributed exactly at
    ingest, so the gap only affects pre-migration history.
    """
    InboundMailbox = apps.get_model("cases", "InboundMailbox")
    EmailMessage = apps.get_model("cases", "EmailMessage")
    for mailbox in InboundMailbox.objects.all().iterator():
        EmailMessage.objects.filter(
            org_id=mailbox.org_id,
            mailbox__isnull=True,
            to_addresses__icontains=mailbox.address,
        ).update(mailbox=mailbox)


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0023_case_merge_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="mailbox",
            field=models.ForeignKey(
                blank=True,
                help_text="The inbound address this message arrived through. Set at ingest; SET_NULL keeps the audit row if the mailbox is later deleted. Null on historical rows the backfill could not attribute.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_messages",
                to="cases.inboundmailbox",
            ),
        ),
        migrations.RunPython(backfill_mailbox, migrations.RunPython.noop),
    ]
