# Generated by Django 6.0.7 on 2026-08-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0024_emailmessage_mailbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="inboundmailbox",
            name="topic_arn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SNS Topic ARN this mailbox accepts mail from. A valid SNS signature only proves a message came from some topic, so the webhook also requires this exact match. Pinned automatically from the first verified SubscriptionConfirmation when left blank; until it is set, notifications are rejected.",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="inboundmailbox",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shared secret used to verify webhook calls. Auto-generated on create if left blank.",
                max_length=128,
            ),
        ),
    ]
