# Generated by Django 6.0.7 on 2026-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0027_alter_casepipeline_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundmailbox",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Reserved for providers that sign deliveries with a shared secret, none of which are implemented yet. Nothing compares this value today: the SES webhook is authenticated by the SNS signature and the topic_arn pin below. Admin-writable so a provider-issued key can be stored, and write-only, so it is never returned by the API.",
                max_length=128,
            ),
        ),
    ]
