# Generated by Django 5.2.8 on 2025-12-02 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account created when this lead was converted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_from_leads",
                to="accounts.account",
            ),
        ),
    ]
