# Generated by Django 5.2.8 on 2025-12-02 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_change_phone_to_charfield"),
        ("leads", "0002_add_converted_account_fk"),
        ("opportunity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="conversion_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When this lead was converted",
                null=True,
                verbose_name="Conversion Date",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_contact",
            field=models.ForeignKey(
                blank=True,
                help_text="Contact created when this lead was converted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_from_leads",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_opportunity",
            field=models.ForeignKey(
                blank=True,
                help_text="Opportunity created when this lead was converted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_from_leads",
                to="opportunity.opportunity",
            ),
        ),
    ]
