# Generated by Django 5.2.8 on 2025-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0006_add_tags_related_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title"
            ),
        ),
    ]
