# Generated by Django 5.2.8 on 2025-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0007_add_title_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="conversion_date",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="converted_account",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="converted_contact",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="converted_opportunity",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="created_from_site",
        ),
        migrations.AlterField(
            model_name="lead",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="Person's job title (e.g., 'VP of Sales', 'CTO')",
                max_length=255,
                null=True,
                verbose_name="Job Title",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Lead name/subject (e.g., 'Enterprise Deal', 'Website Inquiry')",
                max_length=255,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
