# Generated by Django 5.2.8 on 2025-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_remove_unused_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone"
            ),
        ),
    ]
