# Generated by Django 5.2.8 on 2025-12-08 03:05

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower, Length


def cleanup_duplicate_lead_emails(apps, schema_editor):
    """
    Find duplicate lead emails (case-insensitive) within each org
    and clear email on duplicates (keep oldest).
    """
    Lead = apps.get_model("leads", "Lead")

    # Find duplicates: group by lower(email) + org, having count > 1
    duplicates = (
        Lead.objects.exclude(email__isnull=True)
        .exclude(email="")
        .annotate(email_lower=Lower("email"))
        .values("email_lower", "org_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        # Get all leads with this email in this org, ordered by created_at
        leads = list(
            Lead.objects.filter(org_id=dup["org_id"])
            .exclude(email__isnull=True)
            .exclude(email="")
            .annotate(email_lower=Lower("email"))
            .filter(email_lower=dup["email_lower"])
            .order_by("created_at")
        )

        # Keep the first one (oldest), clear email on the rest
        for lead in leads[1:]:
            old_email = lead.email
            lead.email = None
            lead.save(update_fields=["email"])
            print(f"  Cleared duplicate email on lead {lead.id}: '{old_email}'")


def cleanup_long_phone_numbers(apps, schema_editor):
    """
    Truncate phone numbers longer than 25 characters.
    Phone field max_length is being reduced from 50 to 25.
    """
    Lead = apps.get_model("leads", "Lead")

    long_phones = Lead.objects.annotate(phone_len=Length("phone")).filter(
        phone_len__gt=25
    )

    for lead in long_phones:
        old_phone = lead.phone
        lead.phone = lead.phone[:25] if lead.phone else None
        lead.save(update_fields=["phone"])
        print(
            f"  Truncated long phone on lead {lead.id}: '{old_phone}' -> '{lead.phone}'"
        )


def cleanup_invalid_probability(apps, schema_editor):
    """Fix probability values outside 0-100 range."""
    Lead = apps.get_model("leads", "Lead")

    # Set negative probabilities to 0
    updated = Lead.objects.filter(probability__lt=0).update(probability=0)
    if updated:
        print(f"  Set {updated} negative probability values to 0")

    # Set probabilities over 100 to 100
    updated = Lead.objects.filter(probability__gt=100).update(probability=100)
    if updated:
        print(f"  Set {updated} probability values over 100 to 100")


def cleanup_negative_amounts(apps, schema_editor):
    """Set negative opportunity_amount values to NULL."""
    Lead = apps.get_model("leads", "Lead")
    updated = Lead.objects.filter(opportunity_amount__lt=0).update(
        opportunity_amount=None
    )
    if updated:
        print(f"  Set {updated} negative opportunity_amount values to NULL")


def reverse_noop(apps, schema_editor):
    """No reverse operation - data cleanup cannot be undone."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_enable_rls_product_invoice_line_item"),
        ("contacts", "0010_add_enterprise_constraints"),
        ("leads", "0010_add_currency_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Run data cleanup BEFORE adding constraints
        migrations.RunPython(
            cleanup_duplicate_lead_emails,
            reverse_noop,
            elidable=True,
        ),
        migrations.RunPython(
            cleanup_long_phone_numbers,
            reverse_noop,
            elidable=True,
        ),
        migrations.RunPython(
            cleanup_invalid_probability,
            reverse_noop,
            elidable=True,
        ),
        migrations.RunPython(
            cleanup_negative_amounts,
            reverse_noop,
            elidable=True,
        ),
        # Now safe to add constraints
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (7-25 characters, digits and separators only)",
                        regex="^[\\d\\s\\-\\(\\)\\+\\.]{7,25}$",
                    )
                ],
                verbose_name="Phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("org"),
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                name="unique_lead_email_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(("probability__gte", 0), ("probability__lte", 100)),
                name="lead_probability_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("opportunity_amount__gte", 0),
                    ("opportunity_amount__isnull", True),
                    _connector="OR",
                ),
                name="lead_amount_non_negative",
            ),
        ),
    ]
