# Generated by Django 5.2.9 on 2025-12-09 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_add_tag_color_description_isactive"),
        ("contacts", "0010_add_enterprise_constraints"),
        ("leads", "0011_add_enterprise_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="kanban_order",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Order within the kanban column for drag-drop",
                max_digits=15,
                verbose_name="Kanban Order",
            ),
        ),
        migrations.CreateModel(
            name="LeadPipeline",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Pipeline Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If true, new leads without explicit pipeline go here",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_pipelines",
                        to="common.org",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Pipeline",
                "verbose_name_plural": "Lead Pipelines",
                "db_table": "lead_pipeline",
                "ordering": ("-is_default", "name"),
            },
        ),
        migrations.CreateModel(
            name="LeadStage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Stage Name")),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[("open", "Open"), ("won", "Won"), ("lost", "Lost")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "maps_to_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("assigned", "Assigned"),
                            ("in process", "In Process"),
                            ("converted", "Converted"),
                            ("recycled", "Recycled"),
                            ("closed", "Closed"),
                        ],
                        help_text="When lead enters this stage, also update Lead.status",
                        max_length=255,
                        null=True,
                        verbose_name="Maps to Status",
                    ),
                ),
                (
                    "win_probability",
                    models.IntegerField(
                        default=0,
                        help_text="Default probability when lead enters this stage",
                        verbose_name="Default Win Probability %",
                    ),
                ),
                (
                    "wip_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum leads allowed in this stage (null = unlimited)",
                        null=True,
                        verbose_name="WIP Limit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_stages",
                        to="common.org",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="leads.leadpipeline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Stage",
                "verbose_name_plural": "Lead Stages",
                "db_table": "lead_stage",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Current pipeline stage (null = use status-based kanban)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leads.leadstage",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["stage", "kanban_order"], name="lead_stage_i_66ca36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "kanban_order"], name="lead_status_5aa7c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadpipeline",
            index=models.Index(
                fields=["org", "-created_at"], name="lead_pipeli_org_id_23ba65_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadpipeline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("org",),
                name="unique_default_pipeline_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="leadstage",
            index=models.Index(
                fields=["org", "order"], name="lead_stage_org_id_c0f691_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadstage",
            index=models.Index(
                fields=["pipeline", "order"], name="lead_stage_pipelin_63b7e0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leadstage",
            unique_together={("pipeline", "name")},
        ),
    ]
