# Generated by Django 6.0.5 on 2026-05-09 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("macro"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("macro"))


class Migration(migrations.Migration):

    initial = True

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('common', '0018_add_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('scope', models.CharField(choices=[('org', 'Org'), ('personal', 'Personal')], default='org', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macros', to='common.org')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_macros', to='common.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Macro',
                'verbose_name_plural': 'Macros',
                'db_table': 'macro',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['org', 'scope', 'is_active'], name='macro_org_id_baa53d_idx'), models.Index(fields=['owner', '-created_at'], name='macro_owner_i_4b5777_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', True), ('scope', 'org')), models.Q(('owner__isnull', False), ('scope', 'personal')), _connector='OR'), name='macro_scope_owner_consistent')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
