# Generated by Django 2.0 on 2018-04-10 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(blank=True, choices=[(10, 'Account'), (13, 'Lead'), (14, 'Opportunity'), (11, 'Case')], limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'account'), ('model', 'Account'), ('id', 10), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'leads'), ('model', 'Lead'), ('id', 13), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'opportunity'), ('model', 'Opportunity'), ('id', 14), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'cases'), ('model', 'Case'), ('id', 11), _connector='AND'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
